version: '3'
services:
  web:
    build: './web'
    ports:
      - "3000:3000"

  auth:
    build: './auth'
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DB_SERVER=209.97.162.212:27017
  
  objects:
    build: './objects'
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - DB_SERVER=209.97.162.212:27017

  data:
    build: './data'
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - DB_SERVER=209.97.162.212:27017

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/build:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - auth
      - objects
      - data
